# Generated by Django 5.0 on 2024-02-08 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admineapp', '0010_alter_register_address_alter_register_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='address',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='register',
            name='password',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterModelTable(
            name='register',
            table=None,
        ),
    ]
