# Generated by Django 5.0 on 2024-02-08 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admineapp', '0011_alter_register_address_alter_register_password_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='register',
            table='register_table',
        ),
    ]
