# Generated by Django 5.0 on 2024-02-08 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admineapp', '0013_alter_register_address_alter_register_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='phno',
            new_name='phnumber',
        ),
    ]
