# Generated by Django 5.0 on 2024-02-08 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admineapp', '0014_rename_phno_register_phnumber'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register',
        ),
    ]
